In [2]:
import numpy as np
#sektör standartı kullanım budur. Görüp görebileceğiniz bütün kodlarda numpy'ın np şeklinde çağrıldığını göreceksiniz.

Numpy nedir?

Numpy = Numerical Python
Numpy = hızlı vektör ve matris hesaplama kütüphanesidir. Bilimsel hesaplama, veri bilimi, makine öğrenmesi ve görüntü işlemede sıklıkla kullanılır.
Temel veri yapısı ndarray'dir.


In [4]:
#python listeleri birleştirme yapar.
a = [1, 2, 3]
b = [4, 5, 6]

print(a + b)



[1, 2, 3, 4, 5, 6]


In [5]:
#numpy gerçek matematik işlemi yapar.
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

print(a + b)

[5 7 9]


In [11]:
import numpy as np
skaler = np.array(1)

print("Skaler: " , skaler)
print("Skaler boyutu: ", skaler.shape)


Skaler:  1
Skaler boyutu:  ()


In [12]:
import numpy as np
vector = np.array([1,2,3,4,5])

print("Vektör: ", vector)
print("Vektör boyutu: ",  vector.shape)


Vektör:  [1 2 3 4 5]
Vektör boyutu:  (5,)


Vektör boyutu:  (5,) Tek bir boyut bulunmakta.
Bu boyutta 5 tane eleman var.

In [13]:
import numpy as np
matris = np.array([[1,2,3,4,5], 
                   [1,2,3,4,5]])

print("Matris: ", matris)
print("Matris boyutu: ", matris.shape)


Matris:  [[1 2 3 4 5]
 [1 2 3 4 5]]
Matris boyutu:  (2, 5)


Matris boyutu:  (2, 5) parantezde iki eleman var. Matrisin iki boyutu var. İki boyutlu bu matriste iki tane eleman ve bu elemanların da 5'er tane elemanı mevcut.


In [15]:
import numpy as np
matris = np.array([[1,2,3,4,5], 
                   [1,2,3,4,5],[1,2,3,4,5]])

print("Matris: ", matris)
print("Matris boyutu: ", matris.shape)

Matris:  [[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
Matris boyutu:  (3, 5)


Matris boyutu:  (3, 5) Gördüğünüz gibi parantez içindeki eleman sayısı boyutu belirlerken(iki tane), parantezin ilk sayısı en dıştaki boyutta kaç tane eleman olduğunu belirtiyor. 
Bir sonraki sayı(5), bir sonraki boyutta kaçar tane eleman olduğunu belirtiyor.

In [16]:
import numpy as np
tensor = np.array([[[1,2,3,4,5,6],[1,2,3,4,5,6]
                    ], [[1,2,3,4,5,6],[1,2,3,4,5,6]]])

print("Tensor: ", tensor)
print("Tensor boyutu: ", tensor.shape)

Tensor:  [[[1 2 3 4 5 6]
  [1 2 3 4 5 6]]

 [[1 2 3 4 5 6]
  [1 2 3 4 5 6]]]
Tensor boyutu:  (2, 2, 6)


Tensor boyutu:  (2, 2, 6) Aynı mantık burada da geçerli.

In [19]:
import numpy as np
tensor = np.array([[[1,2,3,4,5,6],[1,2,3,4,5,6], [1,2,3,4,5,6]
                    ], [[1,2,3,4,5,6],[1,2,3,4,5,6],[1,2,3,4,5,6]]])

print("Tensor: ", tensor)
print("Tensor boyutu: ", tensor.shape)

Tensor:  [[[1 2 3 4 5 6]
  [1 2 3 4 5 6]
  [1 2 3 4 5 6]]

 [[1 2 3 4 5 6]
  [1 2 3 4 5 6]
  [1 2 3 4 5 6]]]
Tensor boyutu:  (2, 3, 6)


Tensor boyutu:  (2, 3, 6) Ortadaki sayı 2'yken 3 oldu çünkü orta boyuta 1'er eleman daha ekledik.