# Broadcasting

## 1. Broadcasting nedir

Broadcasting, NumPy'nin **farklı shape'lerdeki array'leri** belirli kurallarla **uyumlu hale getirip element-wise işlem yapabilmesidir**.

Kısa tanım:

```text
küçük shape
→ büyük shape'e uyarlanır
→ element-wise işlem yapılır

- Numpy çoğu durumda veriyi gerçekten kopyalamaz.
- Shapeleri mantıksal olarak uyumlu kabul eder
- Sonra işlemi uygular

2. Broadcasting neden gerekli

Broadcasting olmasaydı, çok basit işlemler için bile aynı boyutta array üretilmek zorunda kalınırdı.

In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40])

print("arr:", arr)
print("arr + 5:", arr + 5)

arr: [10 20 30 40]
arr + 5: [15 25 35 45]


Numpy şu şekilde işlem yapıyormuş gibi davranır.

[10, 20, 30, 40] + [5, 5, 5, 5]

Aslında bu array'i oluşturmadan işlem yapar.



3. Broadcasting kuralları

NumPy iki array arasında işlem yaparken shape'leri sağdan sola karşılaştırır.

İki boyut karşılaştırılırken şu kurallar geçerlidir:

Kural 1

Boyutlar eşitse uyumludur.

(2,3)
(2,3)

Kural 2

Boyutlardan biri 1 ise uyumludur.

(2,3)
(1,3)

veya

(4,5,3)
(1,1,3)

Kural 3

Boyutlar eşit değilse ve hiçbirisi 1 değilse broadcasting yapılamaz.

(2,3)
(2,4)

uyumsuzdur.

4. Broadcasting nasıl düşünülmeli

- Adım 1
- Shape'leri yazdır.

#

- Adım 2
- Shape'leri sağdan sola hizala.
#
- Adım 3
- Her eksen için şunu kontrol et:
- eşit mi?
- biri 1 mi?

Eğer her eksende bu koşullardan biri sağlanıyorsa işlem yapılabilir.

Basit örnek: Skaler/Scalar Broadcasting

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print("arr:", arr)
print("arr + 10:", arr + 10)
print("arr * 2:", arr * 2)

arr: [1 2 3 4]
arr + 10: [11 12 13 14]
arr * 2: [2 4 6 8]


In [3]:
import numpy as np

a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print("a:", a)
print("b:", b)
print("a + b:", a + b)

a: [10 20 30]
b: [1 2 3]
a + b: [11 22 33]


In [6]:
import numpy as np

A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

b = np.array([10, 20, 30])

print("A:\n", A)
print("b:", b)
print("A + b:\n", A + b)

print(f"A.shape {A.shape}") #(2,3)
print(f"b.shape {b.shape}") #(3,)


#NumPy bunu sağdan sola şöyle hizalar:
#(2,3)
#(1,3)

A:
 [[1 2 3]
 [4 5 6]]
b: [10 20 30]
A + b:
 [[11 22 33]
 [14 25 36]]
A.shape (2, 3)
b.shape (3,)


In [7]:
import numpy as np

A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

b = np.array([10, 20])

print("A.shape:", A.shape)
print("b.shape:", b.shape)

print(A + b)

A.shape: (2, 3)
b.shape: (2,)


ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

Sebep:

(2,3)
(1,2)

Sağdan sola karşılaştırınca son boyut:

3 vs 2

Ne eşit, ne de biri 1.

Bu yüzden broadcasting yapılamaz.

In [8]:
import numpy as np

A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

v = np.array([10, 20])

print("A:\n", A)
print("v:", v)

A:
 [[1 2 3]
 [4 5 6]]
v: [10 20]


In [9]:
import numpy as np

A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

v = np.array([10, 20])

print("v[:, None]:\n", v[:, None])
print("v[:, None].shape:", v[:, None].shape)
print("A + v[:, None]:\n", A + v[:, None])

v[:, None]:
 [[10]
 [20]]
v[:, None].shape: (2, 1)
A + v[:, None]:
 [[11 12 13]
 [24 25 26]]


In [22]:
import numpy as np

v = np.array([10, 20])

print(f"v.shape {v.shape}")
print(f"v[:, None] : \n {v[:, None]} \n")
print(f"v[:, None].shape : {v[:, None].shape} \n")
print(f"v[None, :] : {v[None, :]} \n")
print(f"v[None, :].shape: {v[None, :].shape}\n ")


v.shape (2,)
v[:, None] : 
 [[10]
 [20]] 

v[:, None].shape : (2, 1) 

v[None, :] : [[10 20]] 

v[None, :].shape: (1, 2)
 


In [23]:
import numpy as np

v = np.array([1, 2, 3])

print("v:", v)
print("v.shape:", v.shape)

print("v[:, None]:\n", v[:, None])
print("v[:, None].shape:", v[:, None].shape)

print("v[None, :]:\n", v[None, :])
print("v[None, :].shape:", v[None, :].shape)

v: [1 2 3]
v.shape: (3,)
v[:, None]:
 [[1]
 [2]
 [3]]
v[:, None].shape: (3, 1)
v[None, :]:
 [[1 2 3]]
v[None, :].shape: (1, 3)


In [24]:
v_col = v[:, np.newaxis]  #np.newaxis ile none aynıdır

print(v_col)
print(v_col.shape)

[[1]
 [2]
 [3]]
(3, 1)


In [26]:
#outer addition 

import numpy as np

a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print("a[:, None] + b:\n", a[:, None] + b)

a[:, None] + b:
 [[11 21 31]
 [12 22 32]
 [13 23 33]]
