Array manüpilasyonu = veriyi değiştirmeden array'in şeklini değiştirmek - birleştirmek - bölmek - eksen yapısını düzenlemek

# Shape değiştirme
- reshape
- flatten
- ravel
- transpose

# eksen ekleme / çıkarma
- np.newaxis
- none
- expand_dims
- squeeze

# birleştirme
- concatenate
- stack
- hstack
- vstack

# bölme
- split
- hsplit
- vsplit


In [1]:
#reshape, array'in shape'ini değiştirir. Veri aynı kalır, sadece düzen değişir.

import numpy as np

arr = np.array([1,2,3,4,5,6])

print("arr:", arr)
print("arr.shape:", arr.shape)

reshaped = arr.reshape(2,3)

print("reshaped:\n", reshaped)
print("reshaped.shape:", reshaped.shape)

#arr.reshape(4,2) olmaz. Toplam eleman sayısı değişmez.

arr: [1 2 3 4 5 6]
arr.shape: (6,)
reshaped:
 [[1 2 3]
 [4 5 6]]
reshaped.shape: (2, 3)


In [2]:
import numpy as np

arr = np.array([1,2,3,4,5,6])

print(arr.reshape(2, -1))
print(arr.reshape(-1, 3))

#-1 kullanmak boyutu sen hesapla demek

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [3]:
#flatten array'i tek boyuta indirir ANCAK copy üretir.
import numpy as np

A = np.array([
    [1,2,3],
    [4,5,6]
])

flat = A.flatten()
flat[0] = 999

print("A:\n", A)
print("flat:", flat)


A:
 [[1 2 3]
 [4 5 6]]
flat: [999   2   3   4   5   6]


In [4]:
#ravel flatten ile aynı işi yapar ama mümkünse view döndürür.

import numpy as np

A = np.array([
    [1,2,3],
    [4,5,6]
])

rav = A.ravel()

print("A:\n", A)
print("rav:", rav)

A:
 [[1 2 3]
 [4 5 6]]
rav: [1 2 3 4 5 6]


In [5]:
#transpose(), eksenlerin yerini değiştirir.
#2d için en bilinen anlamı satırları sütün yapar, sütunları satır yapar.

import numpy as np

A = np.array([
    [1,2,3],
    [4,5,6]
])

print("A:\n", A)
print("A.shape:", A.shape)

T = A.transpose()

#A.T şeklinde kullanımı da vardır.

print("T:\n", T)
print("T.shape:", T.shape)

A:
 [[1 2 3]
 [4 5 6]]
A.shape: (2, 3)
T:
 [[1 4]
 [2 5]
 [3 6]]
T.shape: (3, 2)


In [6]:
#np.newaxis / None yeni eksen eklerler

#sütun vektörü yapımı
import numpy as np

v = np.array([1,2,3])

print("v:", v)
print("v.shape:", v.shape)

v_col = v[:, np.newaxis]

print("v_col:\n", v_col)
print("v_col.shape:", v_col.shape)

v: [1 2 3]
v.shape: (3,)
v_col:
 [[1]
 [2]
 [3]]
v_col.shape: (3, 1)


In [7]:
#satır vektörü yapımı

import numpy as np

v = np.array([1,2,3])

v_row = v[np.newaxis, :]

print("v_row:\n", v_row)
print("v_row.shape:", v_row.shape)

v_row:
 [[1 2 3]]
v_row.shape: (1, 3)


In [8]:
#np.expand_dims() bu da yeni eksen ekler.

import numpy as np

v = np.array([1,2,3])

col = np.expand_dims(v, axis=1)
row = np.expand_dims(v, axis=0)

print("col:\n", col)
print("col.shape:", col.shape)

print("row:\n", row)
print("row.shape:", row.shape)

col:
 [[1]
 [2]
 [3]]
col.shape: (3, 1)
row:
 [[1 2 3]]
row.shape: (1, 3)


In [9]:
#squeeze, boyutu 1 olan eksenleri kaldırır.

import numpy as np

A = np.array([[[1,2,3]]])

print("A.shape:", A.shape)

B = np.squeeze(A)

print("B:", B)
print("B.shape:", B.shape)

A.shape: (1, 1, 3)
B: [1 2 3]
B.shape: (3,)


In [10]:
#concatenate() mevcut eksen boyunca arrayleri birleştirir.
#concatenate için diğer eksenler aynı olmalı

#axis = 0 durumu 

import numpy as np

A = np.array([
    [1,2],
    [3,4]
])

B = np.array([
    [5,6],
    [7,8]
])

C = np.concatenate([A,B], axis=0)

print("C:\n", C)
print("C.shape:", C.shape)

C:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
C.shape: (4, 2)


In [11]:
#axis = 1 durumu

import numpy as np

A = np.array([
    [1,2],
    [3,4]
])

B = np.array([
    [5,6],
    [7,8]
])

C = np.concatenate([A,B], axis=1)

print("C:\n", C)
print("C.shape:", C.shape)

C:
 [[1 2 5 6]
 [3 4 7 8]]
C.shape: (2, 4)


In [12]:
#stack() arrayleri yeni bir eksen oluşturarak birleştirir.

import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

s = np.stack([a,b], axis=0)

print("s:\n", s)
print("s.shape:", s.shape)

s:
 [[1 2 3]
 [4 5 6]]
s.shape: (2, 3)


In [14]:
#axis = 1 

import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

s = np.stack([a,b], axis=1)

print("s:\n", s)
print("s.shape:", s.shape)

s:
 [[1 4]
 [2 5]
 [3 6]]
s.shape: (3, 2)


In [15]:
#hstack ve vstack yatat ve dikey birleştirme için kısayoldur.

import numpy as np

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print(np.hstack([A,B]))



[[1 2 5 6]
 [3 4 7 8]]


In [16]:
import numpy as np

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print(np.vstack([A,B]))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [17]:
#split parçalara böler
import numpy as np

arr = np.array([1,2,3,4,5,6])

parts = np.split(arr, 3)

print(parts)


[array([1, 2]), array([3, 4]), array([5, 6])]


In [18]:
import numpy as np

A = np.array([
    [1,2,3,4],
    [5,6,7,8]
])

parts = np.split(A, 2, axis=1)

for p in parts:
    print(p)

[[1 2]
 [5 6]]
[[3 4]
 [7 8]]


In [19]:
#hsplit ve vsplit kısayol split fonksiyonlarıdır.

import numpy as np

A = np.array([
    [1,2,3,4],
    [5,6,7,8]
])

parts = np.hsplit(A, 2)

for p in parts:
    print(p)

[[1 2]
 [5 6]]
[[3 4]
 [7 8]]


In [20]:
import numpy as np

A = np.array([
    [1,2],
    [3,4],
    [5,6],
    [7,8]
])

parts = np.vsplit(A, 2)

for p in parts:
    print(p)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


 # en sık kullanılanlar

 - reshape
 - flatten
 - ravel
 - transpose
 - np.newaxis
 - concatenate
 - stack
 - split

 #önemli farklar

 - flatten copy
 - ravel mümkünse view

#
 - concatenate - mevcut eksende birleştirir
 - stack - yeni eksen oluşturur

#
 - transpose ekseni değiştirir
 - reshape shape değiştirir, eleman sayısı sabit kalır