# Linear Algebra (NumPy)

Bu bölümde NumPy içinde lineer cebirin en temel işlemleri anlatılır.

Bu konular özellikle:
- matematiksel düşünme
- matris işlemleri
- machine learning temeli
- computer vision dönüşümleri

için önemlidir.

Not:
`transpose` daha önce işlendiği için burada tekrar ana konu gibi değil, gerektiği yerde kısa referans olarak ele alınabilir.

---

## Linear algebra nedir

Linear algebra, vektörler ve matrislerle yapılan matematiksel işlemler alanıdır.

NumPy tarafında bu bölümün temel amacı şudur:

- vektör nedir
- matris nedir
- iki vektör nasıl çarpılır
- iki matris nasıl çarpılır
- bir matrisin tersi nedir
- determinant nedir


In [2]:
#vektör
import numpy as np

v = np.array([1, 2, 3])

print("v:", v)
print("v.shape:", v.shape)

v: [1 2 3]
v.shape: (3,)


In [3]:
#matris
import numpy as np

A = np.array([
    [1, 2],
    [3, 4]
])

print("A:\n", A)
print("A.shape:", A.shape)

A:
 [[1 2]
 [3 4]]
A.shape: (2, 2)


Dot product, iki vektörün çarpılıp toplanmasıdır.
a · b = a1 x b1 + a2 x b2 + a3 x b3 + ...

In [6]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("a:", a)
print("b:", b)

print("np.dot(a, b):", np.dot(a, b))
print("a @ b:", a @ b)

a: [1 2 3]
b: [4 5 6]
np.dot(a, b): 32
a @ b: 32


In [ ]:
import numpy as np

A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

print("A:\n", A)
print("B:\n", B)

print("A * B:\n", A * B) #element - wise çarpım

print("A @ B:\n", A @ B) #matris çarpımnı

#matris çarpımı için boyut şartı (m x n) @ (n x p)

A:
 [[1 2]
 [3 4]]
B:
 [[5 6]
 [7 8]]
A * B:
 [[ 5 12]
 [21 32]]
A @ B:
 [[19 22]
 [43 50]]


In [9]:
#çarpılamayan örnek

A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

C = np.array([
    [1, 2],
    [3, 4]
])

print("A.shape:", A.shape)
print("C.shape:", C.shape)
print(A @ C)

A.shape: (2, 3)
C.shape: (2, 2)


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [10]:
import numpy as np

A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

print("np.matmul(A, B):\n", np.matmul(A, B)) #@ operatörünün karşılığı np.matmul'dur.


np.matmul(A, B):
 [[19 22]
 [43 50]]


In [11]:
#inverse - ters matris
#bir matrisin inverse'ü onu çarptığında birim matris veren tersidir

import numpy as np

A = np.array([
    [1, 2],
    [3, 4]
])

A_inv = np.linalg.inv(A)

print("A:\n", A)
print("A_inv:\n", A_inv)
print("A @ A_inv:\n", A @ A_inv)

A:
 [[1 2]
 [3 4]]
A_inv:
 [[-2.   1. ]
 [ 1.5 -0.5]]
A @ A_inv:
 [[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [13]:
#determinant

import numpy as np

A = np.array([
    [1, 2],
    [3, 4]
])

print("A:\n", A)
print("det(A):", np.linalg.det(A))

A:
 [[1 2]
 [3 4]]
det(A): -2.0000000000000004
