Numpy random modülü rastgele sayı üretmek için kullanılır.

Rastgelelik gerçek rastgelelik değildir ama çoğu uygulama için yeterlidir.

In [1]:
#np.random.seed() tekrarlanabilir rastgelelik için kullanılır.

import numpy as np

np.random.seed(42)
print(np.random.rand(5))

np.random.seed(42)
print(np.random.rand(5))


[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]


In [2]:
#0 ile 1 arasında uniform dağılımlı rastgele sayı üretir.

import numpy as np

print(np.random.rand())

0.15599452033620265


In [3]:
import numpy as np

print(np.random.rand(5)) #1D array

[0.05808361 0.86617615 0.60111501 0.70807258 0.02058449]


In [4]:
import numpy as np

print(np.random.rand(2,3)) #2D Array

[[0.96990985 0.83244264 0.21233911]
 [0.18182497 0.18340451 0.30424224]]


In [7]:
#normal dağılımda rastgele saytı üretir.
#pozitif veya negatif değer olabilir.
#Değerler çoğunlukla 0 çevresindedir.

import numpy as np

print(np.random.randn(5))

[-0.74240684 -0.7033438  -2.13962066 -0.62947496  0.59772047]


In [9]:
#belli aralıkta rastele tam sayı üretir.

import numpy as np

print(np.random.randint(0,10)) #0 dahil 10 hariç

3


In [10]:
import numpy as np

print(np.random.randint(0,256,size=(2,3))) #2D Array

[[ 63 248 130]
 [228  50 134]]


In [11]:
#belli aralıkta uniform dağılımlı float üretir.
import numpy as np

print(np.random.uniform(10,20))

11.705241236872915


In [ ]:
import numpy as np

print(np.random.uniform(10,20,size=(2,3))) #array

[[10.65051593 19.48885537 19.65632033]
 [18.08397348 13.04613769 10.97672114]]


In [14]:
#belirli ortalama ve standart sapma ile normal dağılımdan sayı üretir.


import numpy as np

print(np.random.normal(loc=0, scale=1))


-0.6017066122293969


In [15]:
import numpy as np

print(np.random.normal(loc=100, scale=15, size=5))

[127.78417277  99.79754163  84.13433607 112.33817368  81.68734525]


In [16]:
#bir listeden veya aralıktan rastgele seçim yapar.

import numpy as np

arr = np.array([10,20,30,40,50])

print(np.random.choice(arr))

20


In [17]:
#birden fazla seçim

import numpy as np

arr = np.array([10,20,30,40,50])

print(np.random.choice(arr, size=3))

[20 40 50]


In [19]:
#tekrarsız seçim
import numpy as np

arr = np.array([10,20,30,40,50])

print(np.random.choice(arr, size=3, replace=False))

[10 30 40]


In [20]:
#Bir array'i yerinde karıştırır

import numpy as np

arr = np.array([1,2,3,4,5])

print("önce:", arr)

np.random.shuffle(arr)

print("sonra:", arr)

önce: [1 2 3 4 5]
sonra: [1 5 3 2 4]


In [21]:
#karıştırılmış yeni bir kopya döndürür

import numpy as np

arr = np.array([1,2,3,4,5])

perm = np.random.permutation(arr)

print("arr:", arr)
print("perm:", perm)

arr: [1 2 3 4 5]
perm: [5 3 2 1 4]


Uniform dağılımda belirli aralıktaki tüm değerlerin gelme olasılığı eşittir.

Normal dağılımda, ortalama etrafında yoğunlaşan çan eğrisi dağılımıdır.