# ndarray
Numpy temel veri yapısıdır. N-dimensional array(çok boyutlu dizi) anlamına gelir.

- Tüm elemanlar aynı veri tipindedir.
- Bellekte **contiguous (düz)** tutulur
- hızlı matematik işlemleri yapılabilir.

In [15]:
import numpy as np

#np.array() array oluşturma yollarından biridir.


array_1d = np.array([1,2,3,4,5])
array_2d = np.array([[1,2,3],[1,2,3]])
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print("array_1d:", array_1d, "\n")
print("array_2d: \n", array_2d, "\n")
print("array_3d:\n", array_3d, "\n")



array_1d: [1 2 3 4 5] 

array_2d: 
 [[1 2 3]
 [1 2 3]] 

array_3d:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] 



In [18]:
import numpy as np

arr = np.array([1,2,3,4])

In [19]:
arr.ndim #boyut sayısı

1

In [6]:
arr.shape     # boyut yapısı

(3,)

In [7]:
arr.size      # toplam eleman sayısı

3

In [8]:
arr.dtype     # veri tipi

dtype('int64')

In [9]:
arr.itemsize  # eleman başına byte

8

In [10]:
arr.nbytes    # toplam bellek

24