In [3]:
import numpy as np

#np.array() array oluşturma yollarından biridir.


array_1d = np.array([1,2,3,4,5])
array_2d = np.array([[1,2,3],[1,2,3]])
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print("array_1d:", array_1d, "\n")
print("array_2d: \n", array_2d, "\n")
print("array_3d:\n", array_3d, "\n")



array_1d: [1 2 3 4 5] 

array_2d: 
 [[1 2 3]
 [1 2 3]] 

array_3d:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] 



In [ ]:
import numpy as np

np.arange(10) #0'dan 9'a kadar(parantezin içine girilen sayıdan 1 eksik) 10 tane sayının bulunduğu array oluşturur.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])