In [1]:
#Python liste veya tuple yapılarından array oluşturulabilir.
import numpy as np
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [2]:
import numpy as np

#Birden fazla boyut oluşturmak


array_1d = np.array([1,2,3,4,5])
array_2d = np.array([[1,2,3],[1,2,3]])
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print("array_1d:", array_1d, "\n")
print("array_2d: \n", array_2d, "\n")
print("array_3d:\n", array_3d, "\n")



array_1d: [1 2 3 4 5] 

array_2d: 
 [[1 2 3]
 [1 2 3]] 

array_3d:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] 



In [3]:
#np.zeros() tüm elemanları 0 olan array oluşturur.

import numpy as np

arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [6]:
#np.zeros() tüm elemanları 0 olan array oluşturur.

import numpy as np

arr = np.zeros((3,4)) #2 boyutlu, 4er tane elemanı olan 3 tane listenin olduğu 0'lardan oluşan matris oluşturur.
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
import numpy as np
arr = np.zeros((3,4,5))
arr

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [ ]:
#np.ones np.zeros ile aynı kullanıma sahiptir. Farkı 0 yerine 1 doldurmasıdır.

In [15]:
arr_ones = np.ones(5)
arr_ones_matris = np.ones((2,3))

print("arr_ones:" , arr_ones, "\n")
print("arr_ones_matris: \n", arr_ones_matris)

arr_ones: [1. 1. 1. 1. 1.] 

arr_ones_matris: 
 [[1. 1. 1.]
 [1. 1. 1.]]


In [24]:
np.empty(17)

array([4.67296746e-307, 1.69121096e-306, 1.60221208e-306, 1.86919514e-306,
       8.34441742e-308, 1.78022342e-306, 6.23058028e-307, 9.79107872e-307,
       6.89807188e-307, 7.56594375e-307, 6.23060065e-307, 1.78021527e-306,
       8.34454050e-308, 1.11261027e-306, 1.15706896e-306, 1.33512173e-306,
       3.49698923e-317])

In [17]:
np.empty((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
np.full(5, 7) #tüm elemanlar aynı değer

array([7, 7, 7, 7, 7])

In [43]:
arr = np.array([1,2,3])

#verilen np.array ile aynı boyutta 0 veya 1lerden oluşan np.array oluşturur
arr_zeros_like = np.zeros_like(arr)
arr_ones_like = np.ones_like(arr)

print(arr_zeros_like, "\n")
print(arr_ones_like, "\n")

[0 0 0] 

[1 1 1] 



In [26]:
np.full((3,3), 10) #tüm elemanlar aynı değer.

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [56]:
arr = np.array([1,2,3])

np.full_like(arr, 10)

array([10, 10, 10])

In [27]:
np.arange(5) #range mantığında array oluşturur.

array([0, 1, 2, 3, 4])

In [28]:
np.arange(2,10) #başlangıç, bitiş(ilk elemanı alır, son elemanı almaz.)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.arange(0,10,2) #başlangıç, bitiş, adım

array([0, 2, 4, 6, 8])

In [30]:
np.linspace(0,1,5) #başlangıç ve bitiş arasında eşit aralıklı değerler alır. başlangıç - bitiş - adım sayısı

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [40]:
np.logspace(1,4,4) #başlangıç - Bitiş - Bu Aralıkta kaç tane değer üretilecek. Varsayılan üs tabanı 10dur.
#10^1 10^2 10^3 

array([   10.,   100.,  1000., 10000.])

In [41]:
np.logspace(0,4,5, base=2) #yukarıdaki fonksiyonda varsayılan üs tabanı 10'u burada base parametresi ile taban 2 yapıldı

array([ 1.,  2.,  4.,  8., 16.])

In [44]:
np.eye(3) #birim matris

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [47]:
np.eye(3,5) #kare olmak zorunda değildir.

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [52]:
np.eye(4, k=1) #diagonal kaydırılabilir

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [46]:
np.identity(2) #Birim matris ancak sadece kare şeklinde üretebilir.

array([[1., 0.],
       [0., 1.]])

In [55]:
np.diag([1,2,3,4]) #diogonal matris oluşturur.

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
np.random.rand(5)

np.random.rand(3,3) # 0 - 1 arası rastgele sayı

In [ ]:
np.random.randn(5) #normal dağılım

In [ ]:
np.random.randint(0,10,5) #belli aralıkta random integer

In [ ]:
np.fromfunction(lambda i,j: i+j,(3,3)) #fonksiyon ile array üretir.

In [ ]:
np.fromiter(range(5), dtype=int) #iteratordan array üretir.

In [ ]:
np.frombuffer(b'1234', dtype='S1') #binary bufferdan array üretir.

In [ ]:
b = np.copy(a) #mevcut arrayden kopya üretir.

In [ ]:
np.asarray([1,2,3]) #Verilen veriyi numpy array'e dönüştürür eğer veri zaten numpy array ise kopya oluşturmaz.
#np.array() genelde kopya oluşturur. np.asarray() mümkünse kopya oluşturmaz.

array([1, 2, 3])

- np.array
- np.zeros
- np.ones
- np.full
- np.arange
- np.linspace
- np.eye
- np.random
En sık kullanılanlar