# 1) Indexing
1.1) Indexing nedir?
- Indexing, bir array içindeki tek bir elemana veya belirli bir konuma erişmektir.
- Numpy da Python gibi 0 tabanlı indeksleme kullanır.


In [1]:
import numpy as np

arr = np.array([10,20,30,40])

print("arr[0]: ", arr[0])
print("arr[1]: ", arr[1])
print("arr[2]: ", arr[2])
print("arr[3]: ", arr[3])


arr[0]:  10
arr[1]:  20
arr[2]:  30
arr[3]:  40


1.2) Negatif Indexing

In [3]:
import numpy as np
arr = np.array([10, 20, 30, 40])

print("arr[-1]: ", arr[-1])  
print("arr[-2]: ", arr[-2])  
print("arr[-3]: ", arr[-3])  
print("arr[-4]: ", arr[-4])  

arr[-1]:  40
arr[-2]:  30
arr[-3]:  20
arr[-4]:  10


1.3) 2 boyutlu array'de indexing

In [4]:
import numpy as np

arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("arr[0,0]: ", arr[0, 0])  
print("arr[1,2]: ",arr[1, 2])  
print("arr[2,1]: ",arr[2, 1])  


arr[0,0]:  1
arr[1,2]:  6
arr[2,1]:  8


1.4) 3 boyutlu array'de indexing

In [ ]:
arr = np.array([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])

print("arr[0, 0, 0]: ", arr[0, 0, 0])  
print("arr[1, 1, 0]: ", arr[1, 1, 0])  

arr[0, 0, 0]:  1
arr[1, 1, 0]:  7


# 2) Slicing
- Slicing, array'in bir kısmını almaktır.
- Temel yapı: arr[start:stop:step]
- Önemli nokta: stop değeri dahil değildir.

2.1) 1D Slicing

In [1]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50, 60])

print("arr[1:4]: ", arr[1:4])   # 1 ile 4 arasını al
print("arr[:3]: ",  arr[:3])    # 0'dan 3'e kadar al.
print("arr[3:]: ",  arr[3:])    # 3'den sona kadar al
print("arr[::2]: ", arr[::2])   # Baştan sona 2'şer adımla al.

#stop değeri dahil değildir.

arr[1:4]:  [20 30 40]
arr[:3]:  [10 20 30]
arr[3:]:  [40 50 60]
arr[::2]:  [10 30 50]


2.2) Negatif Slicing

In [3]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50, 60])

print("arr[-4:-1] : ", arr[-4:-1])  # [30 40 50]
print("arr[::-1] :" , arr[::-1])   # [60 50 40 30 20 10] #Negatif Slicing. Array'i ters çevirir. Önemlidir.

arr[-4:-1] :  [30 40 50]
arr[::-1] : [60 50 40 30 20 10]


2.3) 2D Slicing
- Her eksen için ayrı ayrı slicing yapılabilir.

In [6]:
import numpy as np
arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9,10,11,12]
])

print(arr[0:2, 1:3],"\n")
print(arr[0:1, 0:2])

#0:2 -> ilk iki satır
#1:3 -> 2. ve 3. sütun
#arr[satır_aralığı, sütun_aralığı]

[[2 3]
 [6 7]] 

[[1 2]]


2.4) Tüm satır / tüm sütun seçimi

In [9]:
import numpy as np
arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9,10,11,12]
])


print(arr[:, 0], "\n")   # ilk sütun
print(arr[1, :], "\n")   # ikinci satır
print(arr[:, 1:3]) # tüm satırlar, 2-3. sütunlar

[1 5 9] 

[5 6 7 8] 

[[ 2  3]
 [ 6  7]
 [10 11]]


Slicing genelde view döndürür.

In [ ]:
arr = np.array([10, 20, 30, 40])
sub = arr[1:3]

sub[0] = 999

print(arr)  # [ 10 999  30  40] #slicing view döndürür.

[ 10 999  30  40]


In [ ]:
sub = arr[1:3].copy() #gerçek kopya istenirse bu şekilde yapılmalı

In [ ]:
#Mutlaka bilinmesi gerekenler

arr[0]      #ilk eleman
arr[-1]     #son eleman
arr[:3]     #ilk 3 eleman
arr[:-3]    #son 3 eleman
arr[::2]    #her 2 elemandan biri
arr[::-1]   #ters çevirme
arr[:,0]    #ilk sütun
arr[0,:]    #ilk satır
arr[1:2,2:4]    #alt matris
