Fancy Indexing, index olarak liste veya array kullanmaktır. Normal indexingden farkı budur. Normal indexing ve slice genelde view döndürür. Fancy Indexing her zaman copy üretir.
- normal indexing → tek index
- slicing → aralık
- fancy indexing → istediğin index listesi

In [1]:
import numpy as np

arr = np.array([10,20,30,40,50])

arr[[0,2,4]] #belirli elemanları seçmek

array([10, 30, 50])

Fancy indexing her zaman için copy üretir.

In [2]:
import numpy as np


arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

arr[[0,2]] #belirli satırlar

array([[10, 20, 30],
       [70, 80, 90]])

In [3]:
import numpy as np


arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

arr[:, [0,2]] #belirli sütunlar

array([[10, 30],
       [40, 60],
       [70, 90]])

In [4]:
import numpy as np


arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

arr[[0,2], [1,2]] #satır ve sütun seçimi

array([20, 90])

Koordinat bazlı seçim

In [5]:
import numpy as np


arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

rows = np.array([0,2])
cols = np.array([1,2])

arr[rows, cols]


array([20, 90])