- True -> al
- False -> alma

In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
mask = np.array([False, True, False, True, False])

print(arr[mask])

[20 40]


In [ ]:
#koşulla maske üretmek
arr = np.array([10, 20, 30, 40, 50])

mask = arr > 25
print(f"mask: {mask}")
print(f"arr[mask]: {arr[mask]}")

print(arr[arr > 25]) #kısa yazım 



mask: [False False  True  True  True]
arr[mask]: [30 40 50]
[30 40 50]


In [5]:
import numpy as np

arr = np.array([5, 12, 18, 25, 30])

print(arr[arr < 20])

[ 5 12 18]


In [ ]:
#Belirli aralıkta olanları seçmek

import numpy as np


arr = np.array([5, 12, 18, 25, 30, 40])

mask = (arr >= 10) & (arr <= 30)
print(arr[mask])

#& -> AND iki koşul aynı anda sağlanmalı

In [6]:
#negatif değerler
import numpy as np

arr = np.array([-5, 10, -3, 8, 15, -20])

negative_mask = arr < 0
print(arr[negative_mask])

[ -5  -3 -20]


In [7]:
#negatifleri sıfır yapmak

import numpy as np

arr = np.array([-5, 10, -3, 8, 15, -20])

arr[arr < 0] = 0
print(arr)

[ 0 10  0  8 15  0]


In [8]:
#çift sayıları seçmek

import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr[arr % 2 == 0])

[2 4 6 8]


In [ ]:
#2d array'de boolean indexing

import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

mask = arr > 25
print(mask)


print(arr[mask])

# 2D array olsa bile, boolean indexing sonucu çoğu zaman 1D döner.
# Çünkü seçilen elemanlar tek sıra halinde çıkarılır.



[[False False  True]
 [ True  True  True]]
[30 40 50 60]


In [13]:
#satır bazlı seçim
import numpy as np

arr = np.array([
    [10, 20],
    [30, 40],
    [50, 60]
])

row_mask = np.array([True, False, True])

print(arr[row_mask])



[[10 20]
 [50 60]]


In [ ]:
#boolean indexing'de kullanılan temel operatörler

mask = (arr > 10) & (arr < 30) #and
mask = (arr < 10) | (arr > 30) #or

#not
mask = arr > 20
print(arr[~mask]) #20'den büyük olmayanları seç 


# Boolean indexing ve computer vision

- thresholding
- segmentation mask
- ROI filtering
- Parlak/karanlık piksel analizi
- Edge filtering