NumPy’de matematik işlemleri element-wise çalışır.
Yani işlem array’in tamamına uygulanır, tek tek döngü yazılmasına gerek yoktur.


In [1]:
import time

t0 = time.time()
liste= []
for i in range(1_000_000):
    us = i ** 100
    liste.append(us)
t1 = time.time()

print(t1 - t0)



1.2194201946258545


In [3]:
import time
import numpy as np


t0 = time.time()

numpy_liste = np.arange(1_000_000)**100

t1 = time.time()

print(t1-t0)

0.006070137023925781


In [4]:
import numpy as np

a = np.array([10,20,30])
b = np.array([1,2,3])

print("a:",a)
print("b:",b)

print("a+b:",a+b)

a: [10 20 30]
b: [1 2 3]
a+b: [11 22 33]


In [5]:
import numpy as np

a = np.array([10,20,30])
b = np.array([1,2,3])

print("a-b:",a-b)

a-b: [ 9 18 27]


Çarpma matris çarpması değildir.

In [6]:
import numpy as np

a = np.array([2,3,4])
b = np.array([10,20,30])

print("a*b:",a*b)

a*b: [ 20  60 120]


In [7]:
import numpy as np

a = np.array([10,20,30])
b = np.array([2,4,5])

print("a/b:",a/b)

a/b: [5. 5. 6.]


Broadcasting örneği

In [8]:
import numpy as np

arr = np.array([10,20,30])

print("arr+5:",arr+5)
print("arr*2:",arr*2)

arr+5: [15 25 35]
arr*2: [20 40 60]


In [9]:
import numpy as np

A = np.array([
[1,2],
[3,4]
])

B = np.array([
[10,20],
[30,40]
])

print("A+B:\n",A+B)

A+B:
 [[11 22]
 [33 44]]


In [10]:
import numpy as np

arr = np.array([2,3,4])

print("arr**2:",arr**2)

arr**2: [ 4  9 16]


In [15]:
import numpy as np

arr = np.array([1,4,9,16])

print("sqrt:",np.sqrt(arr))

sqrt: [1. 2. 3. 4.]


Diğer önemli fonksiyonlar
- np.sqrt
- np.exp
- np.log
- np.abs
- np.sin
- np.cos
- np.tan

In [ ]:
A * B #element wise
A @ B #matris çarpması
np.matmul(A,B) #matris çarpması

In [19]:
import numpy as np

A = np.array([
[1,2],
[3,4]
])

B = np.array([
[10,20],
[30,40]
])

print("A*B:\n",A*B)
print("A@B:\n",A@B)
print("np.matmul(A,B):\n",np.matmul(A,B))

A*B:
 [[ 10  40]
 [ 90 160]]
A@B:
 [[ 70 100]
 [150 220]]
np.matmul(A,B):
 [[ 70 100]
 [150 220]]
