Skaler - Scalar tek bir sayıdır.
- 5
- 3.14
- -2
- Numpy'de scalar işlem bir array ile tek bir sayı arasında yapılan işlemdir.

In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40])

print("arr:", arr)
print("arr + 5:", arr + 5)

arr: [10 20 30 40]
arr + 5: [15 25 35 45]


In [2]:
import numpy as np

arr = np.array([10, 20, 30, 40])

print("arr:", arr)
print("arr - 3:", arr - 3)

arr: [10 20 30 40]
arr - 3: [ 7 17 27 37]


In [3]:
import numpy as np

arr = np.array([2, 4, 6, 8])

print("arr:", arr)
print("arr * 2:", arr * 2)

arr: [2 4 6 8]
arr * 2: [ 4  8 12 16]


In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40])

print("arr:", arr)
print("arr / 10:", arr / 10) #sonuç float oldu

arr: [10 20 30 40]
arr / 10: [1. 2. 3. 4.]


In [5]:
import numpy as np

arr = np.array([2, 3, 4, 5])

print("arr:", arr)
print("arr ** 2:", arr ** 2)

arr: [2 3 4 5]
arr ** 2: [ 4  9 16 25]


In [6]:
import numpy as np

arr = np.array([5, 10, 15])

print("arr:", arr)
print("arr + (-2):", arr + (-2))
print("arr * -1:", arr * -1)

arr: [ 5 10 15]
arr + (-2): [ 3  8 13]
arr * -1: [ -5 -10 -15]


In [7]:
#Skaler tam sayı olmak zorunda değildir.

import numpy as np

arr = np.array([10, 20, 30])

print("arr:", arr)
print("arr * 0.5:", arr * 0.5)
print("arr + 1.5:", arr + 1.5)

arr: [10 20 30]
arr * 0.5: [ 5. 10. 15.]
arr + 1.5: [11.5 21.5 31.5]


In [8]:
#skaler işlemler sadece 1D array için değildir. Matrislerde de durum aynıdır.

import numpy as np

A = np.array([
    [1, 2],
    [3, 4]
])

print("A:\n", A)
print("A + 10:\n", A + 10)
print("A * 3:\n", A * 3)

A:
 [[1 2]
 [3 4]]
A + 10:
 [[11 12]
 [13 14]]
A * 3:
 [[ 3  6]
 [ 9 12]]


In [10]:
#3D arraylerde de aynı mantıkla çalışır.

import numpy as np

arr = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])

print("arr:\n", arr)
print("arr + 1:\n", arr + 1)


arr:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
arr + 1:
 [[[2 3]
  [4 5]]

 [[6 7]
  [8 9]]]


Skaler işlemler görüntü işleme tarafında şu alanlarda kullanılır.
- Parlaklık arttırma
- Kontrast değiştirme
- Normalizasyon


Skaler işlemlerde dtype'a göre davranış değişir.

In [11]:
import numpy as np

arr = np.array([10, 20, 30], dtype=np.uint8)

print("arr:", arr)
print("dtype:", arr.dtype)
print("arr + 5:", arr + 5)

arr: [10 20 30]
dtype: uint8
arr + 5: [15 25 35]


In [ ]:
import numpy as np

arr = np.array([250, 251, 252], dtype=np.uint8)

print("arr:", arr)
print("arr + 10:", arr + 10) #taşma olur. uint8 : 0 - 255 arasındadır.

arr: [250 251 252]
arr + 10: [4 5 6]


In [15]:
import numpy as np

arr = np.array([250, 251, 252], dtype=np.uint8)

arr = arr.astype(np.int32) + 10

print("arr:", arr)

arr: [260 261 262]


Skaler işlemler broadcastingin en basit halidir.

Skaler işlemler: array ile tek sayı arasındaki işlem
- element-wise çalışır
- vectorized çalışır
- broadcasting'in en basit halidir
- Görüntü işleme tarafında karşılığı vardır
- dtype yüzünden taşma olabilir.