dtype (data type), NumPy array içindeki her elemanın bellekte hangi veri tipi ile tutulduğunu belirtir. NumPy’nin performansının büyük kısmı bu kavrama dayanır çünkü veri tipi:

- kaç byte kullanılacağını
- sayının aralığını
 - matematiksel işlemlerin nasıl davranacağını
belirler.

Computer vision tarafında dtype çok kritik bir konudur çünkü görüntüler aslında sayısal matrislerdir.

In [1]:
import numpy as np

arr = np.array([1,2,3,4])
print(arr.dtype)

int64


In [2]:
arr = np.array([1,2,3,4], dtype=np.float32)

print(arr)
print(arr.dtype)

[1. 2. 3. 4.]
float32


| dtype   | byte |
| ------- | ---- |
| int8    | 1    |
| uint8   | 1    |
| int32   | 4    |
| float32 | 4    |
| float64 | 8    |


#uint8 0-255 arasıdır. Yorum satırını teker teker kaldırıp deneyin.


In [ ]:
import numpy as np

arr = np.zeros((1000,1000), dtype=np.uint8)
print(f"arr: {arr} ")
print(f"arr dtype {arr.dtype}")
#uint8 0-255 arasıdır. Yorum satırını teker teker kaldırıp deneyin.

#arr = np.zeros((1000,1000), dtype=np.uint8) * 255


#arr = np.zeros((1000,1000), dtype=np.uint8) * 256 
#type casting hatası 
#uint8 veri tipinin aralığı 0-255 olduğu için
#256 değeri uint8 içinde temsil edilemez.
#NumPy bu durumda OverflowError üretir.


arr: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]] 
arr dtype uint8


OverflowError: Python integer 256 out of bounds for uint8

In [ ]:
import numpy as np

arr = np.array([250], dtype=np.uint8)

print(arr + 10) #taşma oluşur. 250 + 10 = 260 -> 260 % 255 = 5 #0. indeksten başladığı için 0 - 1 - 2 - 3 - 4 

[4]


- Computer vision problemi — parlaklık artırma
img = 230
bright = img + 50

dtype uint8 ise şu olur 230 + 50 -> 24

In [ ]:
#doğru yöntem

import numpy as np

img = np.array([230,230,230])
img_float = img.astype(np.float32)

bright = img_float + 50

bright = np.clip(bright,0,255).astype(np.uint8) #np.clip iki değer arasında veriyi sınırlar.
bright

array([255, 255, 255], dtype=uint8)

Computer Vision örneği

uint8 veri tipinin aralığı 0-255 olduğu için bu aralığı aşan
işlemler integer overflow üretir. NumPy bu durumda değeri
mod 256 alarak wrap-around davranışı gösterir.

In [ ]:
import numpy as np
import cv2
import matplotlib.pyplot as plt
import os

current_dir = os.getcwd()

parent_dir = os.path.dirname(current_dir)
parent_dir = os.path.dirname(parent_dir)

img_path = os.path.join(parent_dir, "assets", "ornek_goruntu.png")

print(f"Erişilen Yol: {img_path}")

img = cv2.imread(img_path)

if img is None:
    print("Görüntü okunamadı!")
    exit()

print("Görüntü başarıyla yakalandı")

bright = img.copy() +  30

plt.figure(figsize=(10,5))

# original
plt.subplot(1,2,1)
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
plt.title("Original Image")
plt.axis("off")

# mask
plt.subplot(1,2,2)
plt.imshow(cv2.cvtColor(bright, cv2.COLOR_BGR2RGB))
plt.title("Overflow(wrap - around)")
plt.axis("off")

plt.show()

print("dtype:", img.dtype)
print("min:", img.min())
print("max:", img.max())

print("overflow min:", bright.min())
print("overflow max:", bright.max())