In [1]:
import numpy as np
import cv2
import matplotlib.pyplot as plt

In [2]:
img = cv2.imread("ornek_goruntu.png")
img = cv2.resize(img, (640,360))
print("Görüntü boyutu" , img.shape)
img



Görüntü boyutu (360, 640, 3)


array([[[106, 103, 103],
        [105, 102, 102],
        [104, 102, 102],
        ...,
        [206, 194, 185],
        [206, 194, 185],
        [206, 194, 185]],

       [[105, 103, 102],
        [105, 102, 102],
        [104, 102, 101],
        ...,
        [206, 195, 185],
        [206, 195, 185],
        [206, 195, 186]],

       [[105, 103, 103],
        [106, 103, 103],
        [105, 102, 102],
        ...,
        [206, 195, 186],
        [206, 196, 186],
        [207, 196, 187]],

       ...,

       [[ 47,  56,  62],
        [ 48,  56,  62],
        [ 48,  56,  62],
        ...,
        [ 65, 126, 129],
        [ 70, 132, 119],
        [ 69, 131, 123]],

       [[ 47,  56,  62],
        [ 48,  56,  61],
        [ 48,  55,  62],
        ...,
        [ 83, 145, 161],
        [ 76, 139, 148],
        [ 68, 129, 143]],

       [[ 47,  55,  61],
        [ 47,  55,  61],
        [ 46,  55,  61],
        ...,
        [ 85, 145, 161],
        [ 93, 156, 160],
        [ 97, 149, 151]]

Görebileceğiniz gibi dosya 3 boyutlu, 3 kanallı bir numpy ndarray'dir.

In [ ]:
plt.figure()
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
plt.show()

In [ ]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

# resmi oku
img = cv2.imread("ornek_goruntu.png")

# BGR → RGB (matplotlib için gerekli)
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

# parlaklık artır
bright_numpy = img + np.ones(img.shape, dtype=np.uint8) * 50

bright_cv2 = cv2.add(img, np.ones(img.shape, dtype=np.uint8) * 50)

# matplotlib ile göster
plt.figure(figsize=(10,5))

plt.subplot(1,3,1)
plt.imshow(img)
plt.title("Original")
plt.axis("on")

plt.subplot(1,3,2)
plt.imshow(bright_numpy)
plt.title("Numpy")
plt.axis("on")

plt.subplot(1,3,3)
plt.imshow(bright_cv2)
plt.title("CV2")
plt.axis("on")



plt.show()

In [5]:
pixel = np.array([250], dtype=np.uint8)
ten = np.array([10], dtype=np.uint8)

result = cv2.add(pixel, ten, dtype=cv2.CV_8U)

#uint8 tipinin üst sınırı 255'dir. Numpy'da 250 + 10 yaptığınızda 4 sonucu alırsınız çünkü 255i geçtiği vakit 0'dan başlar. OpenCV add fonksiyonunda 255e gelindiği vakit ne eklerseniz ekleyin
#255'de kalır. Üstteki kod çalıştırıldığında görüleceği üzere numpy'da beyazlar siyaha kaymışken opencv'de görsel genel olarak daha parlak bir hale geldi.

print(result)

[[255]
 [  0]
 [  0]
 [  0]]


In [ ]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

# resmi oku
img = cv2.imread("ornek_goruntu.png")

# BGR → RGB (matplotlib için gerekli)
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

# parlaklık artır
dark_numpy = img - np.ones(img.shape, dtype=np.uint8) * 50

dark_cv2 = cv2.subtract(img, np.ones(img.shape, dtype=np.uint8) * 50)

# matplotlib ile göster
plt.figure(figsize=(10,5))

plt.subplot(1,3,1)
plt.imshow(img)
plt.title("Original")
plt.axis("on")

plt.subplot(1,3,2)
plt.imshow(dark_numpy)
plt.title("Numpy")
plt.axis("on")

plt.subplot(1,3,3)
plt.imshow(dark_cv2)
plt.title("CV2")
plt.axis("on")



plt.show()

In [1]:
import cv2
import numpy as np

# 1. DURUM: TOPLAMA (OVERFLOW - ÜSTTEN TAŞMA)
# Hedef: Beyaz piksellerin (255) üzerine çıkıldığında ne olur?
p1 = np.array([[250]], dtype=np.uint8)
p2 = np.array([[20]], dtype=np.uint8)

res_np_add = p1 + p2          # NumPy: (250 + 20) = 270 -> 270 % 256 = 14 (Siyaha yakın)
res_cv_add = cv2.add(p1, p2)  # OpenCV: (250 + 20) = 270 -> Max 255 (Tam Beyaz)

print("--- TOPLAMA (250 + 20) ---")
print(f"NumPy Sonucu (Modulo): {res_np_add}") 
print(f"OpenCV Sonucu (Saturate): {res_cv_add}")


# 2. DURUM: ÇIKARMA (UNDERFLOW - SIFIRIN ALTINA DÜŞME)
# Hedef: Siyah piksellerin (0) altına düşüldüğünde ne olur?
p3 = np.array([[10]], dtype=np.uint8)
p4 = np.array([[30]], dtype=np.uint8)

res_np_sub = p3 - p4               # NumPy: (10 - 30) = -20 -> -20 + 256 = 236 (Parlak Gri)
res_cv_sub = cv2.subtract(p3, p4)  # OpenCV: (10 - 30) = -20 -> Min 0 (Tam Siyah)

print("\n--- ÇIKARMA (10 - 30) ---")
print(f"NumPy Sonucu (Modulo): {res_np_sub}")
print(f"OpenCV Sonucu (Saturate): {res_cv_sub}")


# EĞİTİM NOTU: 
# Eğer NumPy ile OpenCV gibi davranmak isterseniz 'np.clip' kullanmalısınız:
# np.clip(p1.astype(np.int16) + p2, 0, 255).astype(np.uint8)

--- TOPLAMA (250 + 20) ---
NumPy Sonucu (Modulo): [[14]]
OpenCV Sonucu (Saturate): [[255]]

--- ÇIKARMA (10 - 30) ---
NumPy Sonucu (Modulo): [[236]]
OpenCV Sonucu (Saturate): [[0]]


In [ ]:
import cv2
import numpy as np

# DURUM A: Standart Görüntü Tipi (uint8)

#1D array + Python int: OpenCV bunu görüntü işlemi olarak değil, scalar işlemi olarak yorumlar. Python int 30'u (30, 0, 0, 0) tuple'ına çevirir, çıktı float64 olur, saturate çalışmaz.

p_u8 = np.array([10], dtype=np.uint8) 
sub_u8 = cv2.subtract(p_u8, 30)  
print(f"uint8 Sonucu: {sub_u8}") # ÇIKTI: [[-20. -30. -30. -30.]] (0'da sabitlenmedi, eksiye düştü!)

# DURUM B: İşaretli Tip (int16) 
p_i16 = np.array([10], dtype=np.int16)
sub_i16 = cv2.subtract(p_i16, 30)
print(f"int16 Sonucu: {sub_i16}") # Çıktı: [[-20]] (Negatif korunur!)

uint8 Sonucu: [[-20.]
 [-30.]
 [-30.]
 [-30.]]
int16 Sonucu: [[-20.]
 [-30.]
 [-30.]
 [-30.]]


In [8]:
import numpy as np
import cv2

img = np.array([[10, 200, 50]], dtype=np.uint8)

# Scalar: her pikselden aynı değeri çıkar
print(cv2.subtract(img, 30))                              # [[0, 170, 20]]

# Array: her pikselden karşılık gelen değeri çıkar
print(cv2.subtract(img, np.array([[30, 10, 100]], dtype=np.uint8)))  # [[0, 190, 0]]

[[  0 170  20]]
[[  0 190   0]]


In [ ]:
import cv2
import numpy as np

# DURUM A: Görüntü Formatında (2D) ve uint8 Tip
# 1x1 boyutunda (Yükseklik=1, Genişlik=1) karanlık bir piksel
img_u8 = np.array([[10]], dtype=np.uint8)
res_u8 = cv2.subtract(img_u8, 30)

print(f"uint8 Sonucu (Doygunluk VAR):")
print(res_u8)  # Çıktı: [[0]] olacak! Siyahın altına düşmez.

print("-" * 30)

# DURUM B: Görüntü Formatında (2D) ama int32 Tip
img_i32 = np.array([[10]], dtype=np.int32)
res_i32 = cv2.subtract(img_i32, 30)

print(f"int32 Sonucu (Doygunluk YOK):")
print(res_i32) # Çıktı: [[-20]] olacak. Matematiksel hesap yapar.

uint8 Sonucu (Doygunluk VAR):
[[0]]
------------------------------
int32 Sonucu (Doygunluk YOK):
[[-20]]


In [15]:
import numpy as np
import cv2

a = np.array([[100, 150, 200, 250]], dtype=np.uint8)
b = np.array([[2, 2, 2, 2]], dtype=np.uint8)

numpy_result = a * b
opencv_result = cv2.multiply(a, b)

print("a              :", a)
print("NumPy *        :", numpy_result, numpy_result.dtype)
print("cv2.multiply   :", opencv_result, opencv_result.dtype)

a              : [[100 150 200 250]]
NumPy *        : [[200  44 144 244]] uint8
cv2.multiply   : [[200 255 255 255]] uint8


In [18]:
import numpy as np
import cv2

a = np.array([[10, 20, 30, 40]], dtype=np.uint8)
b = np.array([[2, 4, 5, 8]], dtype=np.uint8)

numpy_result = a / b
opencv_result = cv2.divide(a, b)

print("a            :", a)
print("b            :", b)
print("NumPy /      :", numpy_result, numpy_result.dtype)
print("cv2.divide   :", opencv_result, opencv_result.dtype)

a            : [[10 20 30 40]]
b            : [[2 4 5 8]]
NumPy /      : [[5. 5. 6. 5.]] float64
cv2.divide   : [[5 5 6 5]] uint8


In [ ]:
import numpy as np
import cv2
import matplotlib.pyplot as plt

img1 = cv2.imread("ornek_goruntu.png")
img2 = cv2.imread("ornek_goruntu_gece.jpg")

if img1 is None or img2 is None:
    print("Hata: Resim dosyalarından biri bulunamadı!")
else:
    # img1.shape -> (yükseklik, genişlik, kanal)
    # cv2.resize -> (genişlik, yükseklik) bekler
    img2 = cv2.resize(src=img2, dsize=(img1.shape[1], img1.shape[0]))

    # Artık boyutlar aynı, işlem yapabiliriz
    img_birlesik = cv2.addWeighted(src1=img1, alpha=0.3, src2=img2, beta=0.7, gamma=0)

    plt.figure()
    plt.imshow(cv2.cvtColor(img_birlesik, cv2.COLOR_BGR2RGB))
    plt.axis()
    plt.show()