In [9]:
import numpy as np
import cv2

# 11x11 matris, ortada parlak bölge
img = np.zeros((11, 11), dtype=np.uint8)
img[3:8, 3:8] = 200

# Tuz-biber gürültüsü (birkaç nokta)
img_noisy = img.copy()
img_noisy[4, 4] = 255   # tuz
img_noisy[6, 6] = 0     # biber
img_noisy[5, 3] = 255   # tuz
img_noisy[3, 7] = 0     # biber

print("Gürültülü:\n", img_noisy)
print()
print("Blur:\n", cv2.blur(img_noisy, (3,3)))
print()
print("Gaussian:\n", cv2.GaussianBlur(img_noisy, (3,3), 0))
print()
print("Median:\n", cv2.medianBlur(img_noisy, 3))
print()
print("Bilateral:\n", cv2.bilateralFilter(img_noisy, 5, 75, 75))

Gürültülü:
 [[  0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0 200 200 200 200   0   0   0   0]
 [  0   0   0 200 255 200 200 200   0   0   0]
 [  0   0   0 255 200 200 200 200   0   0   0]
 [  0   0   0 200 200 200   0 200   0   0   0]
 [  0   0   0 200 200 200 200 200   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0]]

Blur:
 [[  0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0]
 [  0   0  22  44  67  67  44  22   0   0   0]
 [  0   0  44  95 139 139 111  67  22   0   0]
 [  0   0  73 146 212 206 178 111  44   0   0]
 [  0   0  73 146 212 184 178 111  67   0   0]
 [  0   0  73 139 206 178 178 111  67   0   0]
 [  0   0  44  89 133 111 111  67  44   0   0]
 [  0   0  22  44  67  67  67  44  22   0   0]
 [  0   0   0   0   0   0   0   0   0  